#!/usr/bin/env bash
# A script that will display information about subdomains

func2 () {
	if [ -z "$1" ]
	then
		return
	elif [ -z "$2" ] && [ -n "$1" ]
	then
		rec=$(dig www."$1" | awk '/ANSWER SECTION:/{ getline; print $4; }')
		ip=$(dig www."$1" | awk '/ANSWER SECTION:/{ getline; print $5; }')
		printf "The subdomain www is a %s record and points to %s\n" "$rec" "$ip"
		rec=$(dig lb-01."$1" | awk '/ANSWER SECTION:/{ getline; print $4; }')
		ip=$(dig lb-01."$1" | awk '/ANSWER SECTION:/{ getline; print $5; }')
		printf "The subdomain lb-01 is a %s record and points to %s\n" "$rec" "$ip"
		rec=$(dig web-01."$1" | awk '/ANSWER SECTION:/{ getline; print $4; }')
		ip=$(dig web-01."$1" | awk '/ANSWER SECTION:/{ getline; print $5; }')
		printf "The subdomain web-01 is a %s record and points to %s\n" "$rec" "$ip"
		rec=$(dig web-02."$1" | awk '/ANSWER SECTION:/{ getline; print $4; }')
		ip=$(dig web-02."$1" | awk '/ANSWER SECTION:/{ getline; print $5; }')
		printf "The subdomain web-02 is a %s record and points to %s\n" "$rec" "$ip"
	elif [ -n "$2" ] && [ -n "$1" ]
	then
		rec=$(dig "$2"."$1" | awk '/ANSWER SECTION:/{ getline; print $4; }')
		ip=$(dig "$2"."$1" | awk '/ANSWER SECTION:/{ getline; print $5; }')
		printf "The subdomain %s is a %s record and points to %s\n" "$2" "$rec" "$ip"
	fi

	return 0
}

func2 "$1" "$2"
