#!/usr/bin/env bash
# transfers a file from client to server
i=1
while [ $i -lt 5 ]
do
	if [ -z "${!i}" ]
	then
		echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
		exit 1
	fi
	(( i++ ))
done

scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~
