#!/usr/bin/env bash
# A script that installs and configure HAproxy
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get install -y haproxy=2.6.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
lbal="#HAproxy for web servers\nfrontend web-frontend\n\tbind *:80n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver 7634-web-01 44.210.147.177:80 check\n\tserver 7634-web-02 3.83.35.191:80 check\n"
printf "%s" "$lbal" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
