#!/usr/bin/env bash
# A script that installs and configure HAproxy
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get install -y haproxy=2.0.\*
echo -e "\n#HAproxy for web servers\nfrontend web-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver 7634-web-01 44.210.147.177:80 check\n\tserver 7634-web-02 3.83.35.191:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
