#!/usr/bin/env bash
# A script that displays "To infinity and beyond" indefinitely and "I am invincible!!!" when it receives a SIGTERM signal

_term() {
	echo "I am invincible!!!"
}

trap _term SIGTERM

while 'true'
do
	echo "To infinity and beyond"
	sleep 2
done
