#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd.

# shellcheck disable=SC2034
file="/etc/passwd"

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	printf '%s:%s:%s\n' "$f1" "$f3" "$f6"
done <"$file"
