#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd and tells a story with it

file="/etc/passwd"

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$f1" "$f4" "$f6" "$f7" "$f3" "$f2" "$f5"
done <"$file"
