#!/usr/bin/env bash
# Script printing "Best School" to standard output 10 times using while loop but prints "Hi" after the 9th iteration

i=0
while [ $i -lt 10 ]
do
	echo "Best School"

	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	(( i++ ))
done
