#!/usr/bin/env bash
# Script printing 1..20 to standard output using while loop

i=1
while [ $i -le 20 ]
do
	case $i in
		4)
			printf "%d\nbad luck from China\n" "$i"
			;;
		9)
			printf "%d\nbad luck from Japan\n" "$i"
			;;
		17)
			printf "%d\nbad luck from Italy\n" "$i"
			;;
		*)
			echo "$i"
			;;
	esac

	(( i++ ))
done
