#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes

hr=0
while [ $hr -le 12 ]
do
	printf "Hour: %d\n" "$hr"
	min=1
	while [ $min -lt 60 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( hr++ ))
done
