#!/usr/bin/env bash
# fix web server with two web server config < 7 lines
chmod 644 /etc/nginx/nginx.conf
sed -i '/user/s/.*/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80 /8080 /g' /etc/nginx/sites-available/default
pkill apache2
sudo -H -u nginx bash -c "service nginx start"
